// @flow
const COLOR = {
  red: 'red',
  green: 'green',
  blue: 'blue',
  black: 'black',
  white: 'white',
  yellow: 'yellow',
  gold: 'gold',
  purple: 'purple',
  cyan: 'cyan',
  orange: 'orange',
  orangered: 'orangered',
  pink: 'pink',
  violet: 'violet',
  yellowgreen: 'yellowgreen',
  tomato: 'tomato',
  tan: 'tan', // 茶色,
  snow: 'snow',
  gray: 'gray',
  silver: 'silver',
  skyblue: 'skyblue',
  navy: 'navy', // 海军色,
  brown: 'brown', // 褐色,
  beige: 'beige', // 米色,

  c000: '#000',
  c111: '#111',
  c222: '#222',
  c333: '#333',
  c444: '#444',
  c555: '#555',
  c666: '#666',
  c777: '#777',
  c888: '#888',
  c999: '#999',
  aaa: '#aaa',
  bbb: '#bbb',
  ccc: '#ccc',
  ddd: '#ddd',
  eee: '#eee',
  fff: '#fff',

  // sred: '#f64040',
  sred: 'rgb(245, 0, 87)',
  swhite: '#fdf7f7',
  sgreen: '#00f87f',
  sblue: '#00aada',
  spurple: '#fc46ad',
  sblack: '#000000cc',
}

export default COLOR;
